import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@/app/styles/globals.css"
import { ReactNode } from "react";
import { Toaster } from "react-hot-toast";
import Floatingnavbar from "@/components/floatingnavbar";
const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Reduxprovider{
  children:ReactNode
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className="relative max-w-9xl flex flex-col items-center justify-start no-scrollbar bg-[#0a0a0a]" style={{fontFamily:"'Robotomono',monospace"}}>
           <Floatingnavbar/>
           <div className="w-full pt-14">
             {children}
           </div>
           <Toaster position="top-center"/>
        </body>
    </html>
  );
}
